import { StyleSheet } from 'react-native';
import { COLORS, SIZES, FONTS, SHADOWS } from '../utils/constants';

export default StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ffffff',
  },
  header: {
    paddingTop: 50,
    paddingBottom: 16,
    paddingHorizontal: 30,
    backgroundColor: '#ffffff',
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
    shadowColor: '#000',
    shadowOffset: {
      width: 0,
      height: 1,
    },
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 2,
  },
  headerContent: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    width: '100%',
  },
  logoContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 8,
    paddingVertical: 1,
    backgroundColor: '#7C3AED',
    borderRadius: 8,
    marginRight: 15,
  },
  logoText: {
    fontSize: 20,
    fontFamily: 'Pacifico_400Regular',
    color: '#FDE047',
    fontWeight: '400',
    letterSpacing: 0.6,
  },
  title: {
    fontSize: 18,
    fontFamily: FONTS.bold,
    color: '#1a1a1a',
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  headerIconButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  notificationButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: '#f8f9fa',
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    position: 'relative',
  },
  notificationDot: {
    position: 'absolute',
    top: -2,
    right: -2,
    width: 8,
    height: 8,
    backgroundColor: '#ff4444',
    borderRadius: 4,
  },
  flipCameraButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
  },
  galleryButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: COLORS.accent,
    justifyContent: 'center',
    alignItems: 'center',
    marginLeft: 8,
    position: 'relative',
  },
  galleryButtonText: {
    position: 'absolute',
    top: -8,
    right: -8,
    backgroundColor: '#ff4444',
    color: '#ffffff',
    fontSize: 10,
    fontFamily: FONTS.bold,
    borderRadius: 10,
    minWidth: 16,
    height: 16,
    textAlign: 'center',
    lineHeight: 16,
  },

  // Permission states
  permissionContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  permissionText: {
    fontSize: 18,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    marginTop: 16,
    textAlign: 'center',
  },
  permissionSubtext: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 8,
    textAlign: 'center',
  },

  // Camera
  camera: {
    flex: 1,
  },
  cameraOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.3)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  arFrame: {
    width: 250,
    height: 300,
    borderWidth: 2,
    borderColor: COLORS.accent,
    borderRadius: 12,
    position: 'relative',
  },
  arCorner: {
    position: 'absolute',
    width: 20,
    height: 20,
    borderColor: COLORS.accent,
  },
  arText: {
    color: COLORS.surface,
    fontSize: 16,
    fontFamily: FONTS.medium,
    marginTop: 20,
    textAlign: 'center',
  },
  captureButton: {
    width: 70,
    height: 70,
    borderRadius: 35,
    backgroundColor: 'rgba(255,255,255,0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    marginTop: 40,
    ...SHADOWS.lg,
  },
  captureButtonInner: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: '#ff4757',
  },
  exitCameraButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },

  // Camera placeholder
  cameraPlaceholder: {
    flex: 1,
    backgroundColor: COLORS.primary,
    margin: SIZES.md,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  cameraText: {
    fontSize: 18,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    marginTop: 16,
  },
  cameraSubtext: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: 8,
    textAlign: 'center',
    paddingHorizontal: 40,
  },
  startCameraButton: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: COLORS.accent,
    paddingHorizontal: 20,
    paddingVertical: 12,
    borderRadius: 25,
    marginTop: 20,
    ...SHADOWS.md,
  },
  startCameraButtonText: {
    color: COLORS.surface,
    fontSize: 16,
    fontFamily: FONTS.medium,
    marginLeft: 8,
  },

  // AR Button Container
  arButtonContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    width: '100%',
    paddingHorizontal: SIZES.lg,
    marginTop: SIZES.md,
  },
  wardrobeButton: {
    backgroundColor: COLORS.accent,
    marginRight: SIZES.sm,
  },

  // Modal styles
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  modalTitle: {
    fontSize: 18,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },

  // Gallery Modal
  galleryModal: {
    backgroundColor: COLORS.surface,
    width: '90%',
    height: '80%',
    borderRadius: 12,
    padding: 16,
  },
  doneButton: {
    fontSize: 16,
    color: COLORS.accent,
    fontFamily: FONTS.medium,
  },
  emptyGallery: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyGalleryText: {
    fontSize: 16,
    color: COLORS.textSecondary,
    marginTop: SIZES.md,
  },
  emptyGallerySubtext: {
    fontSize: 14,
    color: COLORS.textSecondary,
    marginTop: SIZES.sm,
  },
  galleryList: {
    flex: 1,
  },
  galleryItem: {
    flexDirection: 'row',
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  galleryImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginRight: 12,
  },
  galleryItemInfo: {
    flex: 1,
    justifyContent: 'center',
  },
  galleryItemDate: {
    fontSize: 14,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  galleryItemCamera: {
    fontSize: 12,
    color: COLORS.textSecondary,
    marginTop: 2,
  },
  galleryItemOutfit: {
    fontSize: 12,
    color: COLORS.accent,
    marginTop: 2,
  },

  // Wardrobe Selector Modal
  wardrobeSelectorModal: {
    backgroundColor: COLORS.surface,
    width: '95%',
    height: '90%',
    borderRadius: 16,
    padding: 16,
  },
  createAvatarButton: {
    fontSize: 16,
    color: COLORS.accent,
    fontFamily: FONTS.medium,
  },
  selectedItemsSummary: {
    backgroundColor: COLORS.background,
    padding: 16,
    borderRadius: 8,
    marginVertical: 8,
  },
  selectedItemsText: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    marginBottom: 4,
  },
  selectedCategoriesText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
  },
  wardrobeCategoriesList: {
    flex: 1,
    marginVertical: 8,
  },
  wardrobeCategorySection: {
    marginBottom: 20,
  },
  categoryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f0f0',
  },
  categoryEmoji: {
    fontSize: 20,
    marginRight: 8,
  },
  categoryTitle: {
    flex: 1,
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.text,
  },
  selectedIndicator: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  categoryItemsScroll: {
    marginVertical: 8,
  },
  wardrobeItem: {
    width: 100,
    backgroundColor: COLORS.surface,
    borderRadius: 12,
    marginHorizontal: 4,
    alignItems: 'center',
    padding: 8,
    borderWidth: 2,
    borderColor: 'transparent',
    ...SHADOWS.sm,
  },
  wardrobeItemSelected: {
    borderColor: COLORS.accent,
    backgroundColor: `${COLORS.accent}10`,
  },
  wardrobeItemImage: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginBottom: 8,
    backgroundColor: COLORS.background,
  },
  wardrobeItemName: {
    fontSize: 12,
    color: COLORS.text,
    textAlign: 'center',
    fontWeight: '500',
  },
  itemSelectedBadge: {
    position: 'absolute',
    top: 4,
    right: 4,
    backgroundColor: COLORS.accent,
    borderRadius: 10,
    width: 20,
    height: 20,
    justifyContent: 'center',
    alignItems: 'center',
  },
  noItemsText: {
    fontSize: 14,
    color: COLORS.textSecondary,
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 16,
  },
  wardrobeActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: '#f0f0f0',
  },
  wardrobeActionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 120,
  },
  cancelButton: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  cancelButtonText: {
    fontSize: 14,
    color: COLORS.text,
    fontFamily: FONTS.medium,
  },
  tryOnButton: {
    backgroundColor: COLORS.accent,
  },
  tryOnButtonText: {
    fontSize: 14,
    color: COLORS.surface,
    fontFamily: FONTS.medium,
    marginLeft: 4,
  },

  // Avatar Preview Modal
  avatarPreviewModal: {
    backgroundColor: COLORS.surface,
    width: '90%',
    maxHeight: '80%',
    borderRadius: 16,
    padding: 20,
  },
  avatarDisplay: {
    alignItems: 'center',
    marginVertical: 20,
  },
  avatarCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: `${COLORS.accent}20`,
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: 12,
    borderWidth: 3,
    borderColor: COLORS.accent,
  },
  avatarEmoji: {
    fontSize: 40,
  },
  avatarTitle: {
    fontSize: 20,
    fontFamily: FONTS.bold,
    color: COLORS.text,
    marginBottom: 4,
  },
  avatarSubtitle: {
    fontSize: 14,
    color: COLORS.textSecondary,
    textAlign: 'center',
  },
  avatarItemsDisplay: {
    marginVertical: 20,
  },
  avatarItemsTitle: {
    fontSize: 16,
    fontFamily: FONTS.medium,
    color: COLORS.text,
    marginBottom: 8,
  },
  avatarItem: {
    alignItems: 'center',
    marginRight: 12,
  },
  avatarItemImage: {
    width: 60,
    height: 60,
    borderRadius: 8,
    marginBottom: 4,
    backgroundColor: COLORS.background,
  },
  avatarItemName: {
    fontSize: 12,
    color: COLORS.text,
    textAlign: 'center',
    maxWidth: 80,
  },
  avatarActions: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginTop: 20,
  },
  avatarActionButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    marginHorizontal: 8,
  },
  backToSelectionButton: {
    backgroundColor: COLORS.background,
    borderWidth: 1,
    borderColor: '#f0f0f0',
  },
  backToSelectionButtonText: {
    fontSize: 14,
    color: COLORS.text,
    fontFamily: FONTS.medium,
  },
});